version: "3.8"
services:
  mongodb:
    networks:
      - krishantha
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  spring-boot-app:
    networks:
      - krishantha
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-app-v1
    container_name: spring-boot-app-v1-container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongo-express:
    networks:
      - krishantha
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  krishantha:
    driver: bridge
